development:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_api_key: <%= ENV['HONEYCOMB_API_KEY'] %>

test:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_api_key: <%= ENV['HONEYCOMB_API_KEY'] %>

staging:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_api_key: <%= ENV['HONEYCOMB_API_KEY'] %>

production:
  database_host: <%= ENV['DATABASE_HOST'] %>
  database_username: <%= ENV['DATABASE_USERNAME'] %>
  database_password: <%= ENV['DATABASE_PASSWORD'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  mailer_from_email: <%= ENV['MAILER_FROM_EMAIL'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  honeycomb_dataset: <%= ENV['HONEYCOMB_DATASET'] %>
  honeycomb_api_key: <%= ENV['HONEYCOMB_API_KEY'] %>
